# Generated by Django 5.2.4 on 2026-08-09 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('marks', models.PositiveSmallIntegerField(choices=[(1, '1 Mark'), (3, '3 Marks'), (8, '8 Marks')])),
                ('mode', models.CharField(choices=[('mcq', 'MCQ'), ('write', 'Write Answer')], default='write', max_length=10)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_option', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expected_components', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='notes.note')),
            ],
        ),
    ]
